/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.ufpe.cin.if688.minijava;

import br.ufpe.cin.if688.minijava.antlr.MiniJavaGrammarLexer;
import br.ufpe.cin.if688.minijava.antlr.MiniJavaGrammarParser;
import br.ufpe.cin.if688.minijava.ast.Program;
import br.ufpe.cin.if688.minijava.util.Programs;
import br.ufpe.cin.if688.minijava.visitor.BuildSymbolTableVisitor;
import br.ufpe.cin.if688.minijava.visitor.MiniJavaVisitor;
import br.ufpe.cin.if688.minijava.visitor.TypeCheckVisitor;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {

        Program program = new MiniJavaVisitor()
                .visit(
                        new MiniJavaGrammarParser(
                                new CommonTokenStream(
                                        new MiniJavaGrammarLexer(
                                                CharStreams.fromString(Programs.input1)
                                        )
                                )
                        ).program());

        BuildSymbolTableVisitor buildSymbolTableVisitor = new BuildSymbolTableVisitor();
        buildSymbolTableVisitor.visit(program);

        System.out.println(buildSymbolTableVisitor.getSymbolTable());

        TypeCheckVisitor typeCheckVisitor = new TypeCheckVisitor(buildSymbolTableVisitor.getSymbolTable());
        typeCheckVisitor.visit(program);
    }
}
